name: Automatic Approve
on:
  schedule:
    - cron: 0 0 * * *
  workflow_dispatch:
jobs:
  automatic-approve:
    name: Automatic Approve
    runs-on: ubuntu-24.04
    steps:
      - name: Automatic Approve
        uses: mheap/automatic-approve-action@v1.1.0
        with:
          token: ${{ secrets.TOKEN_FOR_GITHUB }}
          workflows: "rust.yml,lint.yml"
          dangerous_files: src/main.rs,Cargo.toml,Cargo.lock
